<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class KelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('kelurahans')->insert([
            ['id_kecamatan' => 1, 'nama_kelurahan' => "ALUS ALUS"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "ANA AO"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "BADEGONG"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "BATU RALANG"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "BLANG SEBEL"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "KEBUN BARU"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "LABUHAN BAJAU"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "LABUHAN BAKTI"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "LABUHAN JAYA"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "LATALING"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "LATIUNG"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "PASIR TINGGI"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "PULAU BENGKALAK"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "SEUNEUBOK"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "SUAK LAMATAN"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "ULUL MAYANG"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "TRANS JERNGE"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "TRANS MERANTI"],
            ['id_kecamatan' => 1, 'nama_kelurahan' => "TRANS BARU"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "AIR DINGIN"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "AIR PINANG"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "AMAITENG MULIA"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "AMERIA BAHAGIA"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "GANTING"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "KOTA BATU"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "KUALA MAKMUR"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "LINGGI"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "LUGU"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "PULAU SIUMAT"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "SEFOYAN"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "SINABANG"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "SUAK BULUH"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "SUKA JAYA"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "SUKA KARYA"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "SUKA MAJU"],
            ['id_kecamatan' => 2, 'nama_kelurahan' => "UJUNG TINGGI"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "ANGKEO"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "AWE KECIL"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "AWE SEUBAL"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "BUNON"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "INOR"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "LAAYON"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "LANTIK"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "LEUBANG"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "LEUBANG HULU"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "MAUDIL"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "NAIBOS"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "NANCALA"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "PULAU TEUPAH"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "SALUR"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "SALUR LASENGALU"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "SALUR LATUN"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "SILENGAS"],
            ['id_kecamatan' => 3, 'nama_kelurahan' => "SITAL"],
            ['id_kecamatan' => 4, 'nama_kelurahan' => "LABUAH"],
            ['id_kecamatan' => 4, 'nama_kelurahan' => "NANCAWA"],
            ['id_kecamatan' => 4, 'nama_kelurahan' => "ABAIL"],
            ['id_kecamatan' => 4, 'nama_kelurahan' => "SIMPANG ABAIL"],
            ['id_kecamatan' => 4, 'nama_kelurahan' => "LIANTING"],
            ['id_kecamatan' => 4, 'nama_kelurahan' => "BUSUNG INDAH"],
            ['id_kecamatan' => 4, 'nama_kelurahan' => "KAHAD"],
            ['id_kecamatan' => 4, 'nama_kelurahan' => "MATANURUNG"],
            ['id_kecamatan' => 4, 'nama_kelurahan' => "LASIKIN"],
            ['id_kecamatan' => 4, 'nama_kelurahan' => "SUA-SUA"],
            ['id_kecamatan' => 4, 'nama_kelurahan' => "BATU-BATU"],
            ['id_kecamatan' => 4, 'nama_kelurahan' => "SITUBUK"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "DIHIT"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "KAMPUNG AIE"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "KUTA BARU"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "LAKUBANG"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "LAMAYANG"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "LAMBAYA"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "LATITIK"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "LAUKE"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "LAUREE"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "LAUN SORIP"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "PUTRA JAYA"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "SEBBE"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "SITUFA JAYA"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "SUAK BARU"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "WEL LANGKUM"],
            ['id_kecamatan' => 5, 'nama_kelurahan' => "WEL WEL"],
            ['id_kecamatan' => 6, 'nama_kelurahan' => "BABUSSALAM"],
            ['id_kecamatan' => 6, 'nama_kelurahan' => "BULU HADIK"],
            ['id_kecamatan' => 6, 'nama_kelurahan' => "GUNUNG PUTIH"],
            ['id_kecamatan' => 6, 'nama_kelurahan' => "KUALA BAKTI"],
            ['id_kecamatan' => 6, 'nama_kelurahan' => "KUALA BARU"],
            ['id_kecamatan' => 6, 'nama_kelurahan' => "LUAN BALU"],
            ['id_kecamatan' => 6, 'nama_kelurahan' => "LUGU SEBAHAK"],
            ['id_kecamatan' => 6, 'nama_kelurahan' => "MUARA AMAN"],
            ['id_kecamatan' => 6, 'nama_kelurahan' => "SAMBAY"],
            ['id_kecamatan' => 6, 'nama_kelurahan' => "TANJUNG RAYA"],
            ['id_kecamatan' => 7, 'nama_kelurahan' => "BUBUHAN"],
            ['id_kecamatan' => 7, 'nama_kelurahan' => "KUTA INANG"],
            ['id_kecamatan' => 7, 'nama_kelurahan' => "SIBULUH"],
            ['id_kecamatan' => 7, 'nama_kelurahan' => "KUTA PADANG"],
            ['id_kecamatan' => 7, 'nama_kelurahan' => "AMARABU"],
            ['id_kecamatan' => 7, 'nama_kelurahan' => "LATAK AYAH"],
            ['id_kecamatan' => 7, 'nama_kelurahan' => "BORENGAN"],
            ['id_kecamatan' => 7, 'nama_kelurahan' => "UJUNG PADANG"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "ALONG"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "BUNGA"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "GANANG PUSAKO"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "JAYA BARU"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "KARYA BAKTI"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "KENANGAN JAYA"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "LALLA BAHAGIA"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "MEUNAFAH"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "MUTIARA"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "NASREUHE"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "PADANG UNOI"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "PANTON LAWE"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "SUAK MANANG"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "TAMENG"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "TAMON"],
            ['id_kecamatan' => 8, 'nama_kelurahan' => "UJUNG SALANG"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "AMABAAN"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "BABUL MAKMUR"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "BATU RAGI"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "LAYABAUNG"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "LHOK BIKHAO"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "LHOK MAKMUR"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "MALASIN"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "MITEUM"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "SANGGIRAN"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "SEMBILAN"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "SIGULAI"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "SINAR BAHAGIA"],
            ['id_kecamatan' => 9, 'nama_kelurahan' => "UJUNG HARAPAN"],
            ['id_kecamatan' => 10, 'nama_kelurahan' => "LAFAKHA"],
            ['id_kecamatan' => 10, 'nama_kelurahan' => "LAMEREM"],
            ['id_kecamatan' => 10, 'nama_kelurahan' => "LANGI"],
            ['id_kecamatan' => 10, 'nama_kelurahan' => "LEWAK"],
            ['id_kecamatan' => 10, 'nama_kelurahan' => "LHOK DALAM"],
            ['id_kecamatan' => 10, 'nama_kelurahan' => "LHOK PAUH"],
            ['id_kecamatan' => 10, 'nama_kelurahan' => "LUBUK BAIK"],
            ['id_kecamatan' => 10, 'nama_kelurahan' => "SERAFON"]
            // ['id_kecamatan' => 10, 'nama_kelurahan' => ""],
        ]);
    }
}
